spring:
  application:
    name: usuario
  datasource:
    url: jdbc:mysql://localhost:3306/usuariojdbc?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          connection.provider_disables_autocommit: true
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "*"
  info:
    app:
      name: "@project.name@"
      version: "@project.version@"
  server:
    port: 8081