server:
  port: 8081

spring:
  application:
    name: usuario
  datasource:
    url: jdbc:mysql://localhost:3306/usuariojdbc?serverTimezone=America/Sao_Paulo
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    oracleucp:
      time-to-live-connection-timeout:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka