server:
  port: 8080

spring:
  application:
    name: tarefa-service
  datasource:
    url: jdbc:mysql://localhost:3306/tarefajdc?serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Desabilita Feign e Discovery
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

# Desabilita Eureka
eureka:
  client:
    enabled: false

# Desabilita Feign
feign:
  enabled: false

# Adiciona URL do serviço de usuário
usuario:
  service:
    url: http://localhost:8081   # substitua pela URL real do seu serviço de usuário
