server:
  port: 8080


spring:
  application:
    name: spring.data
  datasource:
    url: jdbc:mysql://localhost:3306/tarefajdc?serverTimezone=America/Sao_Paulo
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
